### ISSUE TITLE
Does the plugin support video streaming?

### ISSUE THREAD

**Issue by Ayame** [macdonst/VideoPlayer#1]
Sorry for posting a question rather than an issue, but I was wondering if your plugin supports video streaming on Android with Phonegap and if so what format the stream needs to be in. 

Thanks!

**Comment by macdonst** [comment]
Yes, it can support streaming. Take a look at the formats that Android supports:

https://developer.android.com/guide/appendix/media-formats.html#core

**Comment by FadyM** [comment]
I am sorry but i am a little bit stuck here I have tried to play back rstp streaming but  i get the error 
04-26 15:58:03.871: E/Web Console(20248): Uncaught Error: Error calling method on NPObject. at 
file:///android_asset/www/Scripts/cordova-2.6.0.js:858

I have tried playing a local video and it works okay 

Thanks!

**Comment by macdonst** [comment]
VideoPlayer does not support rtsp:// urls.

Simon Mac Donald
http://hi.im/simonmacdonald

**Comment by FadyM** [comment]
is there anyway to run the native player through phone gap ? it works well on the native player but i can never open the native player from phonegap

Thank you,

**Comment by macdonst** [comment]
You'd need to write a plugin. You can use this one as a template or feel
free to add the code necessary to play a rtsp url into this plugin. If it
works I will accept the code.

Simon Mac Donald
http://hi.im/simonmacdonald

**Comment by tilakraok** [comment]
Hi..

Dose this plug-in supports rtsp? 

Thank you.

**Comment by macdonst** [comment]
Nope

Simon Mac Donald
http://hi.im/simonmacdonald
