### ISSUE TITLE
Play all video from sdcard

### ISSUE THREAD

**Issue by thenibbana** [macdonst/VideoPlayer#15]
I'm using this plugin that  works fine for online or single url from asset file.
I need to play all the local videos from the sdcard. Is there any way so that i can play all videos?

Thanks!

**Comment by macdonst** [comment]
You just need to call the play method with the file:///sdcard/myvideo.mp4 path set correctly.

**Comment by thenibbana** [comment]
how do i play all video in loop, not only single video?

**Comment by macdonst** [comment]
There is no onActivityResult called from the video player when the video is done. So you'll need to detect that your app has been paused -> Playing Video and resumed -> when the user returns to the app and start playing the next video.
